/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ExperienceSlugRouteImport } from './routes/experience.$slug'
import { Route as AchievementsSlugRouteImport } from './routes/achievements.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSlugRoute = ExperienceSlugRouteImport.update({
  id: '/experience/$slug',
  path: '/experience/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsSlugRoute = AchievementsSlugRouteImport.update({
  id: '/achievements/$slug',
  path: '/achievements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/achievements/$slug'
    | '/experience/$slug'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/achievements/$slug'
    | '/experience/$slug'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/achievements/$slug'
    | '/experience/$slug'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AchievementsSlugRoute: typeof AchievementsSlugRoute
  ExperienceSlugRoute: typeof ExperienceSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$slug': {
      id: '/experience/$slug'
      path: '/experience/$slug'
      fullPath: '/experience/$slug'
      preLoaderRoute: typeof ExperienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/$slug': {
      id: '/achievements/$slug'
      path: '/achievements/$slug'
      fullPath: '/achievements/$slug'
      preLoaderRoute: typeof AchievementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AchievementsSlugRoute: AchievementsSlugRoute,
  ExperienceSlugRoute: ExperienceSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
